### ISSUE TITLE
[Bug]: Failed to run `config` for nvim-recorder

### ISSUE THREAD

**Issue by emrhnpla02** [chrisgrieser/nvim-recorder#10]
### Bug Description

I got the error below when I try to run `recorder.setup()`

```
Failed to run `config` for nvim-recorder

...02/.local/share/nvim/lazy/nvim-recorder/lua/recorder.lua:293: bad argument #1 to 'pairs' (table expected, got nil)
```

Here is my config if it'll be helpful
```lua
local status_ok, recorder = pcall(require, "recorder")
if not status_ok then
  vim.notify("Recorder not found!")
  return
end

recorder.setup({
  slots = { "a", "b" },
  mapping = {
    startStopRecording = "q",
    playMacro = "Q",
    editMacro = "cq",
    switchSlot = "<C-A-q>",
  },
  clear = false,
  logLevel = vim.log.levels.INFO,
  dapSharedKeymaps = false,
})
```

### To Reproduce

1. Call `require('recorder').setup` in nvim config
2. Open neovim

### neovim version

```Text
NVIM v0.10.0-dev-737+gdf2f5e391
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by darenharre11** [comment]
Same issue here. Have not been able to solve.

**Comment by chrisgrieser** [comment]
oh sorry everyone, I accidentally deleted one of the config lines when refactoring the code earlier today 🤦‍♂️ 

Just pushed a fix
