### ISSUE TITLE
[Bug]: Log levels for notify are not respected

### ISSUE THREAD

**Issue by al1-ce** [chrisgrieser/nvim-recorder#18]
### Bug Description

Log levels for notify are not respected, all notifications currently are considered to be Info

### Relevant Screenshot

Current:
![image](https://github.com/chrisgrieser/nvim-recorder/assets/60989682/beacd179-11f0-4e4f-b5cb-76acf44c3260)

Should be - none

### To Reproduce

Config:
```lua
require("recorder").setup {
	logLevel = vim.log.levels.DEBUG,
}
```

Changing `vim.log.levels.DEBUG` to `"debug"` doesn't help

### neovim version

```Text
v0.9.5
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed
