### ISSUE TITLE
[Bug]: Custom keymaps don't clear default ones

### ISSUE THREAD

**Issue by serhez** [chrisgrieser/nvim-recorder#19]
### Bug Description

I have defined custom keymaps such as:

```lua
mapping = {
    startStopRecording = "m",
    playMacro = "M",
    switchSlot = "<C-m>",
    editMacro = "cm",
    yankMacro = "ym", -- also decodes it for turning macros to mappings
    deleteAllMacros = "dm",
    addBreakPoint = "##", -- this should be a string you don't use in insert mode during a macro
},
```

However, when pressing `q`, the recorder is still triggered. Is this a bug or is there a way to deactivate default mappings?

### To Reproduce

Use the config above, press `q` and run the command `lua vim.notify(require("recorder").recordingStatus())`.

### neovim version

```Text
Nightly.
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
I cannot reproduce this, changing mappings works fine for me.

Could you paste your full config with how you set it up in your plugin manager?

**Comment by serhez** [comment]
Thanks for the reply! Here it goes:

```lua
local M = {
   "chrisgrieser/nvim-recorder",
   event = "BufRead",
}

function M.config()
   require("recorder").setup({
      mapping = {
         startStopRecording = "m",
         playMacro = "M",
         switchSlot = "<C-m>",
         editMacro = "cm",
         yankMacro = "ym", -- also decodes it for turning macros to mappings
         deleteAllMacros = "dm",
         addBreakPoint = "##", -- this should be a string you don't use in insert mode during a macro
      },

      -- Share keymaps with nvim-dap
      dapSharedKeymaps = false,

      -- clears all macros-slots on startup
      clear = false,

      -- log level used for any notification, mostly relevant for nvim-notify
      -- (note that by default, nvim-notify does not show the levels trace and debug.)
      logLevel = vim.log.levels.INFO,

      -- if enabled, only essential or critical notifications are sent.
      -- If you do not use a plugin like nvim-notify, set this to `true`
      -- to remove otherwise annoying notifications.
      lessNotifications = false,
    })
end

return M
```

**Comment by serhez** [comment]
I have a component in `lualine` which shows when the recorder is active, which is how I first noticed. Then, I checked the result of `require("recorder").recordingStatus()` to confirm that the recording was being triggered when pressing `q`.

**Comment by serhez** [comment]
Also, it may be useful to know that the `m` mappings also work, so the config is being read correctly.

**Comment by chrisgrieser** [comment]
Oh, I see now. Yeah, nvim-recorder does not disable the native macro functionality from nvim. What happens is when you press `q`, you simply trigger nvim's regular macro recording, without the addition from nvim-recorder. `require("recorder").recordingStatus()` is not able to differentiate whether you use nvim or nvim-recorder (since nvim-recorder is basically a wrapper around nvim's functionality anyway.)

This will btw happen with any plugin – if you have a plugin that improves nvim's `w` motion, but map it to `m`, then `w` will still perform nvim's regular `w` motion.

You can disable nvim's macro (or any nvim keymapping, for that matter) by using `:h <Nop>`:
```lua
vim.keymap.set("n", "q", "<Nop>")
```
