### ISSUE TITLE
Feature Request: Abitilty to disable keymaps

### ISSUE THREAD

**Issue by nishantpillai5** [chrisgrieser/nvim-recorder#21]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

Don't set keymaps if set to `false`. Allow users to explicitly disable keymaps they don't use.

```lua
  require('recorder').setup {
    mapping = {
      addBreakPoint = false,
    },
  }
```

**Comment by chrisgrieser** [comment]
Vim already has a builtin way to disable mappings, namely`:h <Nop>`. Just enter `<Nop>` as string and the mappings are disabled.
