### ISSUE TITLE
Feature Request: document ability to customize bottom statusline, not just tabline

### ISSUE THREAD

**Issue by jondkinney** [chrisgrieser/nvim-recorder#23]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

In the [minimal config for lazy loading](https://github.com/chrisgrieser/nvim-recorder#lazy-loading-the-plugin) you specify `tabline`, which looks nice when populated, but I don't want to have the tabline always visible. So I'd prefer to customize the already always visible statusline. It's a one word change in the config.

```lua
    require("lualine").setup {
      sections = {
        lualine_y = lualineY,
        lualine_z = lualineZ,
      },
    }
```
Note: `sections` is used instead of `tabline`

**Comment by chrisgrieser** [comment]
Optimizing lazy loading like that is mostly for advanced users - the resistive section is in the super section "advanced usage" after all. 

I think it is not inappropriate to expect from advanced users to be able to figure out a customization like that on their own.
