### ISSUE TITLE
[Bug]: When using special keys macro are not recorded properly

### ISSUE THREAD

**Issue by sudo-tee** [chrisgrieser/nvim-recorder#8]
### Bug Description

When using keys that are not "printable" as start `startStopRecording`  the macro will be trimmed and not complete.

I identified where the issue is Happening

![image](https://github.com/chrisgrieser/nvim-recorder/assets/342110/0a73f9bd-870d-4ac7-b1cc-8c0e868d387b)

since the macro is cut weather or not the key is present, it will then remove part of the actual macro.  

In my case the translated key is "`<lt<f4>`" 

Here is my config
```
return {
  "chrisgrieser/nvim-recorder",
  opts = {
    mapping = {
      startStopRecording = "<F4>",
      playMacro = "<F5>",
      switchSlot = "<leader>ms",
      editMacro = "<leader>me",
      yankMacro = "<leader>my", -- also decodes it for turning macros to mappings
      addBreakPoint = "##", -- ⚠️ this should be a string you don't use in insert mode during a macro
    },
    dapSharedKeymaps = false,
  },
}

```

Thanks a lot for your great little plugin :) 

### neovim version

```Text
NVIM v0.10.0-dev
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thank you!

Well, I haven't thought about the F-keys since I do not have a keyboard with F keys anymore 😆 

I am not super knowledgeable with such non-printable key stuff. Since you apparently know more about it than me, could you simply make a PR? I can merge it right away
